### ISSUE TITLE
name collision with `matplotlib.pylab`

### ISSUE THREAD

**Issue by tacaswell** [javipalanca/pylab#1]
The name `pylab` has been part of the matplotlib name space since 2004 (
https://github.com/matplotlib/matplotlib/commit/f210efb0a#diff-474f6c019adc7eda0f098ff1bd1af36e)

You should probably re-name your project and remove it from pypi as it as already causing confusion for users (http://stackoverflow.com/questions/30880407/pylab-does-not-have-any-attrs).

attn @mdboom @efiring

**Comment by mstimberg** [comment]
+1 for renaming/removing this package, we had users with the same issue. It is very tempting to do `pip install pylab` if `from pylab import *` fails...

**Comment by mdboom** [comment]
I'm sure this comes an annoyance to your project...  I've been in a similar situation in the past for other things.  Please do let us know if there's anything we can do to help with this...

**Comment by fbender** [comment]
Renaming the project would be good. I got really confused looking through the dependencies for another project. 

For the name I propose `scibag`, which reflects the scientific character of this meta package ("a bag of science-related modules"), and most importantly, it is unused and has no related "python scibag" Google search results. Alternatively, `scibox` may be used, however it is too close to the name of the [sciboxes project](https://sciboxes.github.io/), IMHO.

With the [`obsoletes`](https://docs.python.org/2/distutils/setupscript.html#relationships-between-distributions-and-packages) field you can easily mark the old package as obsolete (you may want to add the `Development Status :: 7 - Inactive` classifier to the existing package, though; also see pypa/warehouse#345), and once you renamed this repository, people will be redirected automatically to the "new" package on GitHub. 

I'd be happy to prepare one or two PRs for that, just let me know!

**Comment by fbender** [comment]
Renaming the project would be good. I got really confused looking through the dependencies for another project. 

For the name I propose `scibag`, which reflects the scientific character of this meta package ("a bag of science-related modules"), and most importantly, it is unused and has no related "python scibag" Google search results. Alternatively, `scibox` may be used, however it is too close to the name of the [sciboxes project](https://sciboxes.github.io/), IMHO.

With the [`obsoletes`](https://docs.python.org/2/distutils/setupscript.html#relationships-between-distributions-and-packages) field you can easily mark the old package as obsolete (you may want to add the `Development Status :: 7 - Inactive` classifier to the existing package, though; also see pypa/warehouse#345), and once you renamed this repository, people will be redirected automatically to the "new" package on GitHub. 

@javipalanca, I'd be happy to prepare one or two PRs for that, just let me know!

**Comment by javipalanca** [comment]
I'd be glad to receive a PR!

**Comment by fbender** [comment]
Cool! Are you OK with the proposed `scibag`?

**Comment by javipalanca** [comment]
Yes! It's ok for me! thanks!

**Comment by fbender** [comment]
@javipalanca Did you manage to look into #4? This issue is a soft pre-requirement to fixing this bug.

**Comment by javipalanca** [comment]
Sorry, had been out for a while. But the PR is now merged. Thanks!

**Comment by jenshnielsen** [comment]
This is really annoying as it breaks any code that imports pylab e.g 

```
from pylab import *
```

or any other import from pylab

I just helped a colleague who had this installed and was trying to get some legacy code using pylab running

**Comment by ikirker** [comment]
What still needs to happen before PyLab (this one, not a MatPlotLib one) is removed from the listing on PyPi? As long as it's hanging around there, it's going to continue causing namespace problems.

**Comment by fbender** [comment]
Sorry, I was unable to continue to work on this and will be so for another few months (unless some unexpected spare time comes up).

First things first: For backwards compatibility, it's probably not getting removed anytime soon from PyPI, unfortunately. 

Here's what I recommend to do:
1. Add a note to the README like `***This is not the pylab interface of matplotlib, just a meta-package bundling matplotlib and other libraries!***` and `*This project will be renamed to **scibag-full** to avoid confusion*`. Also Update `history.rst` with the current date and publish as v0.1.4 on PyPI (with the changes in #4 this will mark the package as inactive).
2. Rename every mention of `pylab` to `scibag-full` and clean up (e.g. you don't need manifest, makefile, or the `pylab` folder at all). Also rename repository! Github will add redirection.
3. Add `obsoletes='pylab'` field to `setup.py`
4. Bump version to v1, update `HISTORY.rst` and publish v1 as a new package on PyPI
5. After a year or more, you may want to unpublish the original `pylab` package from PyPI. But this will break something somewhere!

Publishing and renaming the repo requires cooperation by @javipalanca, rest can be prepared and submitted as PRs. 

If I'm not getting to step 1 the next couple of days, feel free to take over.

**Comment by jenshnielsen** [comment]
Sorry but the very existence of this package under that name on pypi causes a much larger backwards incompatibility issue. 

This package breaks any code that does 

```
from pylab import *
```

or any other pylab import since it replaces pylab from matplotlib with an empty package. 

That has been around for 10 years+

Consider the following realistic scenario.

you have code that does

```
from pylab import *
```

which fails. Naturally you assume that this is solved by doing 

```
pip install pylab
```

which does install matplotlib and numpy as you want but it also installs a pylab package that shadows the one from matplotlib. At the very least that package should be renamed to something else.

```
(pylabpackage) ✔ ~ ipython
Python 3.5.2 (default, Jul 28 2016, 21:28:00)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from pylab import show
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-74df56ba1eec> in <module>()
----> 1 from pylab import show

ImportError: cannot import name 'show'
```

This can then be solved by:

```
(pylabpackage) ✔ ~ pip uninstall pylab
Uninstalling pylab-0.1.3:
  /Users/jhn/Envs/pylabpackage/lib/python3.5/site-packages/pylab-0.1.3.dist-info/DESCRIPTION.rst
  /Users/jhn/Envs/pylabpackage/lib/python3.5/site-packages/pylab-0.1.3.dist-info/INSTALLER
  /Users/jhn/Envs/pylabpackage/lib/python3.5/site-packages/pylab-0.1.3.dist-info/METADATA
  /Users/jhn/Envs/pylabpackage/lib/python3.5/site-packages/pylab-0.1.3.dist-info/RECORD
  /Users/jhn/Envs/pylabpackage/lib/python3.5/site-packages/pylab-0.1.3.dist-info/WHEEL
  /Users/jhn/Envs/pylabpackage/lib/python3.5/site-packages/pylab-0.1.3.dist-info/metadata.json
  /Users/jhn/Envs/pylabpackage/lib/python3.5/site-packages/pylab-0.1.3.dist-info/top_level.txt
  /Users/jhn/Envs/pylabpackage/lib/python3.5/site-packages/pylab/__init__.py
  /Users/jhn/Envs/pylabpackage/lib/python3.5/site-packages/pylab/__pycache__/__init__.cpython-35.pyc
  /Users/jhn/Envs/pylabpackage/lib/python3.5/site-packages/pylab/__pycache__/pylab.cpython-35.pyc
  /Users/jhn/Envs/pylabpackage/lib/python3.5/site-packages/pylab/pylab.py
Proceed (y/n)? y
  Successfully uninstalled pylab-0.1.3
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(pylabpackage) ✔ ~ ipython
Python 3.5.2 (default, Jul 28 2016, 21:28:00)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from pylab import show
/Users/jhn/Envs/pylabpackage/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
```

**Comment by javipalanca** [comment]
fixed

**Comment by fbender** [comment]
Thanks! The `pylab` package has disappeared from PyPI, let's see how that pans out. @javipalanca could you please add a further note to the `README`, e.g.: 

> This package used to be called `pylab` but was renamed due to name collision with the `pylab` interface of `matplotlib`. 

Also, you marked the `scibag` package as obsolete and you forgot to add an `obsoletes='pylab'` field to `setup.py`. May you please fix that as well? Thanks!

**Comment by tacaswell** [comment]
Thanks!

**Comment by javipalanca** [comment]
@fbender done.
